# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Simone Tolomei
email: tolomei.simone5#gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Robotics Engineering student & maker
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tolomeis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SimoneTolomei
github_username:  tolomeis

# Build settings
markdown: kramdown
#remote_theme: pages-themes/cayman@v0.2.0
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-include-cache


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# **********************  THEME SETTINGS ************************
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: false